CREATE TABLE ErrorLog
(
    LogID INT IDENTITY(1,1) PRIMARY KEY,
    ProcedureName NVARCHAR(255) NOT NULL,
    ErrorMessage NVARCHAR(MAX) NOT NULL,
    LogDateTime DATETIME NOT NULL DEFAULT GETDATE()
);

ALTER TABLE ErrorLog ADD frmName VARCHAR(200),FormName VARCHAR(200), Category VARCHAR(10), UserId INT