USE [LEASINGDB]
---[tblUnitReference]---

CREATE INDEX [IdxtblUnitReference_RecId]
    ON [dbo].[tblUnitReference] ([RecId]);
CREATE INDEX [IdxtblUnitReference_RefId]
    ON [dbo].[tblUnitReference] ([RefId]);
CREATE INDEX [IdxtblUnitReference_ProjectId]
    ON [dbo].[tblUnitReference] ([ProjectId]);
CREATE INDEX [IdxtblUnitReference_InquiringClient]
    ON [dbo].[tblUnitReference] ([InquiringClient]);
CREATE INDEX [IdxtblUnitReference_ClientMobile]
    ON [dbo].[tblUnitReference] ([ClientMobile]);
CREATE INDEX [IdxtblUnitReference_UnitId]
    ON [dbo].[tblUnitReference] ([UnitId]);
CREATE INDEX [IdxtblUnitReference_UnitNo]
    ON [dbo].[tblUnitReference] ([UnitNo]);
CREATE INDEX [IdxtblUnitReference_StatDate]
    ON [dbo].[tblUnitReference] ([StatDate]);
CREATE INDEX [IdxtblUnitReference_FinishDate]
    ON [dbo].[tblUnitReference] ([FinishDate]);
CREATE INDEX [IdxtblUnitReference_TransactionDate]
    ON [dbo].[tblUnitReference] ([TransactionDate]);
CREATE INDEX [IdxtblUnitReference_Rental]
    ON [dbo].[tblUnitReference] ([Rental]);
CREATE INDEX [IdxtblUnitReference_SecAndMaintenance]
    ON [dbo].[tblUnitReference] ([SecAndMaintenance]);
CREATE INDEX [IdxtblUnitReference_TotalRent]
    ON [dbo].[tblUnitReference] ([TotalRent]);
CREATE INDEX [IdxtblUnitReference_SecDeposit]
    ON [dbo].[tblUnitReference] ([SecDeposit]);
CREATE INDEX [IdxtblUnitReference_Total]
    ON [dbo].[tblUnitReference] ([Total]);
CREATE INDEX [IdxtblUnitReference_EncodedBy]
    ON [dbo].[tblUnitReference] ([EncodedBy]);
CREATE INDEX [IdxtblUnitReference_EncodedDate]
    ON [dbo].[tblUnitReference] ([EncodedDate]);
CREATE INDEX [IdxtblUnitReference_LastCHangedBy]
    ON [dbo].[tblUnitReference] ([LastCHangedBy]);
CREATE INDEX [IdxtblUnitReference_LastChangedDate]
    ON [dbo].[tblUnitReference] ([LastChangedDate]);
CREATE INDEX [IdxtblUnitReference_IsActive]
    ON [dbo].[tblUnitReference] ([IsActive]);
CREATE INDEX [IdxtblUnitReference_ClientID]
    ON [dbo].[tblUnitReference] ([ClientID]);
CREATE INDEX [IdxtblUnitReference_IsPaid]
    ON [dbo].[tblUnitReference] ([IsPaid]);
CREATE INDEX [IdxtblUnitReference_IsDone]
    ON [dbo].[tblUnitReference] ([IsDone]);
CREATE INDEX [IdxtblUnitReference_HeaderRefId]
    ON [dbo].[tblUnitReference] ([HeaderRefId]);
CREATE INDEX [IdxtblUnitReference_IsSignedContract]
    ON [dbo].[tblUnitReference] ([IsSignedContract]);
CREATE INDEX [IdxtblUnitReference_IsUnitMove]
    ON [dbo].[tblUnitReference] ([IsUnitMove]);
CREATE INDEX [IdxtblUnitReference_IsTerminated]
    ON [dbo].[tblUnitReference] ([IsTerminated]);
CREATE INDEX [IdxtblUnitReference_GenVat]
    ON [dbo].[tblUnitReference] ([GenVat]);
CREATE INDEX [IdxtblUnitReference_WithHoldingTax]
    ON [dbo].[tblUnitReference] ([WithHoldingTax]);
CREATE INDEX [IdxtblUnitReference_IsUnitMoveOut]
    ON [dbo].[tblUnitReference] ([IsUnitMoveOut]);
CREATE INDEX [IdxtblUnitReference_FirstPaymentDate]
    ON [dbo].[tblUnitReference] ([FirstPaymentDate]);
CREATE INDEX [IdxtblUnitReference_ContactDoneDate]
    ON [dbo].[tblUnitReference] ([ContactDoneDate]);
CREATE INDEX [IdxtblUnitReference_SignedContractDate]
    ON [dbo].[tblUnitReference] ([SignedContractDate]);
CREATE INDEX [IdxtblUnitReference_UnitMoveInDate]
    ON [dbo].[tblUnitReference] ([UnitMoveInDate]);
CREATE INDEX [IdxtblUnitReference_UnitMoveOutDate]
    ON [dbo].[tblUnitReference] ([UnitMoveOutDate]);
CREATE INDEX [IdxtblUnitReference_TerminationDate]
    ON [dbo].[tblUnitReference] ([TerminationDate]);
CREATE INDEX [IdxtblUnitReference_AdvancePaymentAmount]
    ON [dbo].[tblUnitReference] ([AdvancePaymentAmount]);
CREATE INDEX [IdxtblUnitReference_IsFullPayment]
    ON [dbo].[tblUnitReference] ([IsFullPayment]);
CREATE INDEX [IdxtblUnitReference_PenaltyPct]
    ON [dbo].[tblUnitReference] ([PenaltyPct]);
CREATE INDEX [IdxtblUnitReference_IsPartialPayment]
    ON [dbo].[tblUnitReference] ([IsPartialPayment]);
CREATE INDEX [IdxtblUnitReference_FirtsPaymentBalanceAmount]
    ON [dbo].[tblUnitReference] ([FirtsPaymentBalanceAmount]);
CREATE INDEX [IdxtblUnitReference_Unit_IsNonVat]
    ON [dbo].[tblUnitReference] ([Unit_IsNonVat]);
CREATE INDEX [IdxtblUnitReference_Unit_BaseRentalVatAmount]
    ON [dbo].[tblUnitReference] ([Unit_BaseRentalVatAmount]);
CREATE INDEX [IdxtblUnitReference_Unit_BaseRentalWithVatAmount]
    ON [dbo].[tblUnitReference] ([Unit_BaseRentalWithVatAmount]);
CREATE INDEX [IdxtblUnitReference_Unit_BaseRentalTax]
    ON [dbo].[tblUnitReference] ([Unit_BaseRentalTax]);
CREATE INDEX [IdxtblUnitReference_Unit_TotalRental]
    ON [dbo].[tblUnitReference] ([Unit_TotalRental]);
CREATE INDEX [IdxtblUnitReference_Unit_SecAndMainAmount]
    ON [dbo].[tblUnitReference] ([Unit_SecAndMainAmount]);
CREATE INDEX [IdxtblUnitReference_Unit_SecAndMainVatAmount]
    ON [dbo].[tblUnitReference] ([Unit_SecAndMainVatAmount]);
CREATE INDEX [IdxtblUnitReference_Unit_SecAndMainWithVatAmount]
    ON [dbo].[tblUnitReference] ([Unit_SecAndMainWithVatAmount]);
CREATE INDEX [IdxtblUnitReference_Unit_Vat]
    ON [dbo].[tblUnitReference] ([Unit_Vat]);
CREATE INDEX [IdxtblUnitReference_Unit_Tax]
    ON [dbo].[tblUnitReference] ([Unit_Tax]);
CREATE INDEX [IdxtblUnitReference_Unit_TaxAmount]
    ON [dbo].[tblUnitReference] ([Unit_TaxAmount]);
CREATE INDEX [IdxtblUnitReference_Unit_IsParking]
    ON [dbo].[tblUnitReference] ([Unit_IsParking]);
CREATE INDEX [IdxtblUnitReference_Unit_ProjectType]
    ON [dbo].[tblUnitReference] ([Unit_ProjectType]);
CREATE INDEX [IdxtblUnitReference_Unit_AreaTotalAmount]
    ON [dbo].[tblUnitReference] ([Unit_AreaTotalAmount]);
CREATE INDEX [IdxtblUnitReference_Unit_AreaSqm]
    ON [dbo].[tblUnitReference] ([Unit_AreaSqm]);
CREATE INDEX [IdxtblUnitReference_Unit_AreaRateSqm]
    ON [dbo].[tblUnitReference] ([Unit_AreaRateSqm]);
CREATE INDEX [IdxtblUnitReference_IsRenewal]
    ON [dbo].[tblUnitReference] ([IsRenewal]);