SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



--SET QUOTED_IDENTIFIER ON|OFF
--SET ANSI_NULLS ON|OFF
--GO
CREATE PROCEDURE [dbo].[sp_UpdateAnnouncement] @Message AS NVARCHAR(MAX) = ''
-- WITH ENCRYPTION, RECOMPILE, EXECUTE AS CALLER|SELF|OWNER| 'user_name'
AS
BEGIN
    UPDATE [dbo].[tblAnnouncement]
    SET [tblAnnouncement].[AnnounceMessage] = @Message

	IF @@ROWCOUNT > 0
	BEGIN
	SELECT 'SUCCESS' AS Message_Code
	END

END
GO
