CREATE TABLE [dbo].[tblUnitReference]
(
[RecId] [int] NOT NULL IDENTITY(10000000, 1),
[RefId] AS ('REF'+CONVERT([varchar](MAX),[RecId],(0))),
[ProjectId] [int] NULL,
[InquiringClient] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClientMobile] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UnitId] [int] NULL,
[UnitNo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StatDate] [date] NULL,
[FinishDate] [date] NULL,
[TransactionDate] [date] NULL,
[Rental] [decimal] (18, 2) NULL,
[SecAndMaintenance] [decimal] (18, 2) NULL,
[TotalRent] [decimal] (18, 2) NULL,
[SecDeposit] [decimal] (18, 2) NULL,
[Total] [decimal] (18, 2) NULL,
[EncodedBy] [int] NULL,
[EncodedDate] [datetime] NULL,
[LastCHangedBy] [int] NULL,
[LastChangedDate] [datetime] NULL,
[IsActive] [bit] NULL,
[ComputerName] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClientID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsPaid] [bit] NULL,
[IsDone] [bit] NULL,
[HeaderRefId] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsSignedContract] [bit] NULL,
[IsUnitMove] [bit] NULL,
[IsTerminated] [bit] NULL,
[GenVat] [decimal] (18, 2) NULL,
[WithHoldingTax] [decimal] (18, 2) NULL,
[IsUnitMoveOut] [bit] NULL,
[FirstPaymentDate] [datetime] NULL,
[ContactDoneDate] [datetime] NULL,
[SignedContractDate] [datetime] NULL,
[UnitMoveInDate] [datetime] NULL,
[UnitMoveOutDate] [datetime] NULL,
[TerminationDate] [datetime] NULL,
[AdvancePaymentAmount] [decimal] (18, 2) NULL,
[IsFullPayment] [bit] NULL,
[PenaltyPct] [decimal] (18, 2) NULL,
[IsPartialPayment] [bit] NULL,
[FirtsPaymentBalanceAmount] [decimal] (18, 2) NULL
) ON [PRIMARY]
GO
