CREATE TABLE [dbo].[tblClientMstr]
(
[RecId] [int] NOT NULL IDENTITY(10000000, 1),
[ClientID] AS ([ClientType]+CONVERT([varchar](10),[RecId],(0))),
[ClientType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClientName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age] [int] NULL,
[PostalAddress] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateOfBirth] [date] NULL,
[Gender] [bit] NULL,
[TelNumber] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Nationality] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Occupation] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AnnualIncome] [decimal] (18, 2) NULL,
[EmployerName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmployerAddress] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpouseName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChildrenNames] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalPersons] [int] NULL,
[MaidName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DriverName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VisitorsPerDay] [int] NULL,
[IsTwoMonthAdvanceRental] [bit] NULL,
[IsThreeMonthSecurityDeposit] [bit] NULL,
[Is10PostDatedChecks] [bit] NULL,
[IsPhotoCopyValidID] [bit] NULL,
[Is2X2Picture] [bit] NULL,
[BuildingSecretary] [int] NULL,
[EncodedDate] [datetime] NULL,
[EncodedBy] [int] NULL,
[LastChangedBy] [int] NULL,
[LastChangedDate] [datetime] NULL,
[IsActive] [bit] NULL,
[ComputerName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsMap] [bit] NULL,
[TIN_No] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
