CREATE TABLE [dbo].[tblMonthLedger]
(
[Recid] [bigint] NOT NULL IDENTITY(1, 1),
[ReferenceID] [bigint] NULL,
[ClientID] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LedgMonth] [date] NULL,
[LedgAmount] [decimal] (18, 2) NULL,
[IsPaid] [bit] NULL,
[EncodedBy] [int] NULL,
[EncodedDate] [datetime] NULL,
[ComputerName] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransactionID] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsHold] [bit] NULL,
[BalanceAmount] [decimal] (18, 2) NULL,
[PenaltyAmount] [decimal] (18, 2) NULL,
[ActualAmount] [decimal] (18, 2) NULL,
[LedgRentalAmount] [decimal] (18, 2) NULL,
[Remarks] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unit_ProjectType] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unit_IsNonVat] [bit] NULL,
[Unit_BaseRentalVatAmount] [decimal] (18, 2) NULL,
[Unit_BaseRentalWithVatAmount] [decimal] (18, 2) NULL,
[Unit_BaseRentalTax] [decimal] (18, 2) NULL,
[Unit_TotalRental] [decimal] (18, 2) NULL,
[Unit_SecAndMainAmount] [decimal] (18, 2) NULL,
[Unit_SecAndMainVatAmount] [decimal] (18, 2) NULL,
[Unit_SecAndMainWithVatAmount] [decimal] (18, 2) NULL,
[Unit_Vat] [decimal] (18, 2) NULL,
[Unit_Tax] [decimal] (18, 2) NULL,
[Unit_TaxAmount] [decimal] (18, 2) NULL,
[Unit_IsParking] [bit] NULL,
[Unit_AreaTotalAmount] [decimal] (18, 2) NULL,
[Unit_AreaSqm] [decimal] (18, 2) NULL,
[Unit_AreaRateSqm] [decimal] (18, 2) NULL,
[IsRenewal] [bit] NULL,
[CompanyORNo] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REF] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BNK_ACCT_NAME] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BNK_ACCT_NUMBER] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BNK_NAME] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SERIAL_NO] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModeType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CompanyPRNo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankBranch] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
